package net.zjedu.monitor.bean;

public class DataDetail {
	public String xzqhdm;

	public int year;
	public String xzqhmc;
	//基本情况指标
//	public int A1;
//	public int A2;
//	public int A3;
//	public int A4;
//	public int A5;
//	public int A6;
//	public int A7;
//	public int A8;
//	public int A9;
//	public int A10;
//	public int A11;
//	public int A12;
//	public int A13;
//	public int A14;
//	public int A15;
//	public int A16;
//	public int A17;
//	public int A18;
//	public int A19;
//	public int A20;
//	public int A21;
//	public int A22;
//	public int A23;
//	public int A24;
//	public int A25;
	//教育经费投入指标，B表
	
	public double A1;
	public double A2;
	public double A3;
	public double A4;
	public double A5;
	public double A6;
	public double A7;
	public double A8;
	public double A9;
	public double A10;
	public double A11;
	public double A12;
	public double A13;
	public double A14;
	public double A15;
	public double A16;
	public double A17;
	public double A18;
	public double A19;
	public double A20;
	public double A21;
	public double A22;
	public double A23;
	public double A24;
	public double A25;
	public double B1A;
	public double B1B;
	public double B2A;
	public double B2B;
	public double B3A;
	public double B3B;
	public double B4A;
	public double B4B;
	public double B5;
	public double B6A;
	public double B6B;
	public double B7A;
	public double B7B;
	public double B8A;
	public double B8B;
	public double B9A;
	public double B9B;
	public double B10A;
	public double B10B;
	public double B11A;
	public double B11B;
	public double B12A;
	public double B12B;
	public double B13A;
	public double B13B;
	public double B14A;
	public double B14B;
	public double B15A;
	public double B15B;
	public double B16A;
	public double B16B;
	public double B17A;
	public double B17B;
	public double B18A;
	public double B18B;
	public double B19;
	public double B20;
	public double B21;
	public double B22;
	public double B23;
	public double B24;
	public double B25;
	public double B26A;
	public double B26B;
	public double B27A;
	public double B27B;
	public double B28A;
	public double B28B;
	public double B29A;
	public double B29B;
	public double B30A;
	public double B30B;
	public double B31A;
	public double B31B;
	public double B32A;
	public double B32B;
	public double B33A;
	public double B33B;
	public double B34A;
	public double B34B;
	public double B35A;
	public double B35B;
	public double B36A;
	public double B36B;
	public double B37A;
	public double B37B;
	public double B38A;
	public double B38B;
	public double B39A;
	public double B39B;
	public double B40A;
	public double B40B;
	public double B41A;
	public double B41B;
	public double B42A;
	public double B42B;
	public double B43A;
	public double B43B;
	public double C1;
	public double C2;
	public double C3;
	public double C4;
	public double C5;
	public double C6;
	public double C7;
	public double C8;
	public double C9;
	public double C10;
	public double C11;
	public double C12;
	public double C13;
	public double C14;
	public double C15;
	public double C16;
	public double C17;
	public double C18;
	public double C19;
	public double C20;
	public double C21;
	public double C22;
	public double C23;
	public double C24;
	public double C25;
	public double C26;
	public double C27;
	public double C28;
	public double C29;
	public double C30;
	public double C31;
	public double C32;
	public double C33;
	public double C34;
	public double C35;
	public double C36;
	public double C37;
	public double C38;
	public double C39;
	public double C40;
	public double C41;
	public double C42;
	public double C43;
	public double C44;
	public double C45;
	public double C46;
	public double C47;
	public double D1;
	public double D2;
	public double D3;
	public double D4;
	public double D5;
	public double D6;
//	public double ;
//	public double ;
	public double D7;
	public double D8;
	public double D9;
//	public double D11/D10;
//	public double D12/D13;
//	public double (D14+D16)/(D15+D17);
//	public double D18/D19;
	public double D20;
	public double D21;
//	public double D22/D23;
	public double D24;
	public double D25;
	public double D26;
	public double D27;
//	public double D28/D29;
	public double E1;
	public double E2;
	public double E3;
	public double E4;
	public double E5;
	public double E6;
	public double E7;
	public double E8;
	public double E9;
	public double E10;
	public double E11;
	public double E12;
	public double E13;
	public double E14;
	public double E15;
	public double E16;
	public double E17;
	public double E18;
	public double E19;
	public double E20;
	public double E21;
	public double E22;
	public double E23;
//	public double E24/E21;
	public double E25;
	public double E26;
	public double E27;
	public double E28;
	public double E29;
	public double E30;
}
